// utils/countries.js
export const countries = [
  { name: "Afghanistan", code: "AF", flagCode: "af" },
  { name: "Afrique du Sud", code: "ZA", flagCode: "za" },
  { name: "Albanie", code: "AL", flagCode: "al" },
  { name: "Algérie", code: "DZ", flagCode: "dz" },
  { name: "Allemagne", code: "DE", flagCode: "de" },
  { name: "Andorre", code: "AD", flagCode: "ad" },
  { name: "Angola", code: "AO", flagCode: "ao" },
  { name: "Antigua-et-Barbuda", code: "AG", flagCode: "ag" },
  { name: "Arabie saoudite", code: "SA", flagCode: "sa" },
  { name: "Argentine", code: "AR", flagCode: "ar" },
  { name: "Arménie", code: "AM", flagCode: "am" },
  { name: "Australie", code: "AU", flagCode: "au" },
  { name: "Autriche", code: "AT", flagCode: "at" },
  { name: "Azerbaïdjan", code: "AZ", flagCode: "az" },
  { name: "Bahamas", code: "BS", flagCode: "bs" },
  { name: "Bahreïn", code: "BH", flagCode: "bh" },
  { name: "Bangladesh", code: "BD", flagCode: "bd" },
  { name: "Barbade", code: "BB", flagCode: "bb" },
  { name: "Belgique", code: "BE", flagCode: "be" },
  { name: "Bélize", code: "BZ", flagCode: "bz" },
  { name: "Bénin", code: "BJ", flagCode: "bj" },
  { name: "Bhoutan", code: "BT", flagCode: "bt" },
  { name: "Biélorussie", code: "BY", flagCode: "by" },
  { name: "Birmanie", code: "MM", flagCode: "mm" },
  { name: "Bolivie", code: "BO", flagCode: "bo" },
  { name: "Bosnie-Herzégovine", code: "BA", flagCode: "ba" },
  { name: "Botswana", code: "BW", flagCode: "bw" },
  { name: "Brésil", code: "BR", flagCode: "br" },
  { name: "Brunei", code: "BN", flagCode: "bn" },
  { name: "Bulgarie", code: "BG", flagCode: "bg" },
  { name: "Burkina Faso", code: "BF", flagCode: "bf" },
  { name: "Burundi", code: "BI", flagCode: "bi" },
  { name: "Cambodge", code: "KH", flagCode: "kh" },
  { name: "Cameroun", code: "CM", flagCode: "cm" },
  { name: "Canada", code: "CA", flagCode: "ca" },
  { name: "Cap-Vert", code: "CV", flagCode: "cv" },
  { name: "Chili", code: "CL", flagCode: "cl" },
  { name: "Chine", code: "CN", flagCode: "cn" },
  { name: "Chypre", code: "CY", flagCode: "cy" },
  { name: "Colombie", code: "CO", flagCode: "co" },
  { name: "Comores", code: "KM", flagCode: "km" },
  { name: "Congo", code: "CG", flagCode: "cg" },
  { name: "Congo (RDC)", code: "CD", flagCode: "cd" },
  { name: "Corée du Nord", code: "KP", flagCode: "kp" },
  { name: "Corée du Sud", code: "KR", flagCode: "kr" },
  { name: "Costa Rica", code: "CR", flagCode: "cr" },
  { name: "Côte d'Ivoire", code: "CI", flagCode: "ci" },
  { name: "Croatie", code: "HR", flagCode: "hr" },
  { name: "Cuba", code: "CU", flagCode: "cu" },
  { name: "Danemark", code: "DK", flagCode: "dk" },
  { name: "Djibouti", code: "DJ", flagCode: "dj" },
  { name: "Dominique", code: "DM", flagCode: "dm" },
  { name: "Égypte", code: "EG", flagCode: "eg" },
  { name: "Émirats arabes unis", code: "AE", flagCode: "ae" },
  { name: "Équateur", code: "EC", flagCode: "ec" },
  { name: "Érythrée", code: "ER", flagCode: "er" },
  { name: "Espagne", code: "ES", flagCode: "es" },
  { name: "Estonie", code: "EE", flagCode: "ee" },
  { name: "Eswatini", code: "SZ", flagCode: "sz" },
  { name: "États-Unis", code: "US", flagCode: "us" },
  { name: "Éthiopie", code: "ET", flagCode: "et" },
  { name: "Fidji", code: "FJ", flagCode: "fj" },
  { name: "Finlande", code: "FI", flagCode: "fi" },
  { name: "France", code: "FR", flagCode: "fr" },
  { name: "Gabon", code: "GA", flagCode: "ga" },
  { name: "Gambie", code: "GM", flagCode: "gm" },
  { name: "Géorgie", code: "GE", flagCode: "ge" },
  { name: "Ghana", code: "GH", flagCode: "gh" },
  { name: "Grèce", code: "GR", flagCode: "gr" },
  { name: "Grenade", code: "GD", flagCode: "gd" },
  { name: "Guatemala", code: "GT", flagCode: "gt" },
  { name: "Guinée", code: "GN", flagCode: "gn" },
  { name: "Guinée équatoriale", code: "GQ", flagCode: "gq" },
  { name: "Guinée-Bissau", code: "GW", flagCode: "gw" },
  { name: "Guyana", code: "GY", flagCode: "gy" },
  { name: "Haïti", code: "HT", flagCode: "ht" },
  { name: "Honduras", code: "HN", flagCode: "hn" },
  { name: "Hongrie", code: "HU", flagCode: "hu" },
  { name: "Inde", code: "IN", flagCode: "in" },
  { name: "Indonésie", code: "ID", flagCode: "id" },
  { name: "Irak", code: "IQ", flagCode: "iq" },
  { name: "Iran", code: "IR", flagCode: "ir" },
  { name: "Irlande", code: "IE", flagCode: "ie" },
  { name: "Islande", code: "IS", flagCode: "is" },
  { name: "Israël", code: "IL", flagCode: "il" },
  { name: "Italie", code: "IT", flagCode: "it" },
  { name: "Jamaïque", code: "JM", flagCode: "jm" },
  { name: "Japon", code: "JP", flagCode: "jp" },
  { name: "Jordanie", code: "JO", flagCode: "jo" },
  { name: "Kazakhstan", code: "KZ", flagCode: "kz" },
  { name: "Kenya", code: "KE", flagCode: "ke" },
  { name: "Kirghizistan", code: "KG", flagCode: "kg" },
  { name: "Kiribati", code: "KI", flagCode: "ki" },
  { name: "Koweït", code: "KW", flagCode: "kw" },
  { name: "Laos", code: "LA", flagCode: "la" },
  { name: "Lesotho", code: "LS", flagCode: "ls" },
  { name: "Lettonie", code: "LV", flagCode: "lv" },
  { name: "Liban", code: "LB", flagCode: "lb" },
  { name: "Libéria", code: "LR", flagCode: "lr" },
  { name: "Libye", code: "LY", flagCode: "ly" },
  { name: "Liechtenstein", code: "LI", flagCode: "li" },
  { name: "Lituanie", code: "LT", flagCode: "lt" },
  { name: "Luxembourg", code: "LU", flagCode: "lu" },
  { name: "Macédoine du Nord", code: "MK", flagCode: "mk" },
  { name: "Madagascar", code: "MG", flagCode: "mg" },
  { name: "Malaisie", code: "MY", flagCode: "my" },
  { name: "Malawi", code: "MW", flagCode: "mw" },
  { name: "Maldives", code: "MV", flagCode: "mv" },
  { name: "Mali", code: "ML", flagCode: "ml" },
  { name: "Malte", code: "MT", flagCode: "mt" },
  { name: "Maroc", code: "MA", flagCode: "ma" },
  { name: "Marshall", code: "MH", flagCode: "mh" },
  { name: "Maurice", code: "MU", flagCode: "mu" },
  { name: "Mauritanie", code: "MR", flagCode: "mr" },
  { name: "Mexique", code: "MX", flagCode: "mx" },
  { name: "Micronésie", code: "FM", flagCode: "fm" },
  { name: "Moldavie", code: "MD", flagCode: "md" },
  { name: "Monaco", code: "MC", flagCode: "mc" },
  { name: "Mongolie", code: "MN", flagCode: "mn" },
  { name: "Monténégro", code: "ME", flagCode: "me" },
  { name: "Mozambique", code: "MZ", flagCode: "mz" },
  { name: "Namibie", code: "NA", flagCode: "na" },
  { name: "Nauru", code: "NR", flagCode: "nr" },
  { name: "Népal", code: "NP", flagCode: "np" },
  { name: "Nicaragua", code: "NI", flagCode: "ni" },
  { name: "Niger", code: "NE", flagCode: "ne" },
  { name: "Nigéria", code: "NG", flagCode: "ng" },
  { name: "Norvège", code: "NO", flagCode: "no" },
  { name: "Nouvelle-Zélande", code: "NZ", flagCode: "nz" },
  { name: "Oman", code: "OM", flagCode: "om" },
  { name: "Ouganda", code: "UG", flagCode: "ug" },
  { name: "Ouzbékistan", code: "UZ", flagCode: "uz" },
  { name: "Pakistan", code: "PK", flagCode: "pk" },
  { name: "Palaos", code: "PW", flagCode: "pw" },
  { name: "Panama", code: "PA", flagCode: "pa" },
  { name: "Papouasie-Nouvelle-Guinée", code: "PG", flagCode: "pg" },
  { name: "Paraguay", code: "PY", flagCode: "py" },
  { name: "Pays-Bas", code: "NL", flagCode: "nl" },
  { name: "Pérou", code: "PE", flagCode: "pe" },
  { name: "Philippines", code: "PH", flagCode: "ph" },
  { name: "Pologne", code: "PL", flagCode: "pl" },
  { name: "Portugal", code: "PT", flagCode: "pt" },
  { name: "Qatar", code: "QA", flagCode: "qa" },
  { name: "Roumanie", code: "RO", flagCode: "ro" },
  { name: "Royaume-Uni", code: "GB", flagCode: "gb" },
  { name: "Russie", code: "RU", flagCode: "ru" },
  { name: "Rwanda", code: "RW", flagCode: "rw" },
  { name: "Saint-Christophe-et-Niévès", code: "KN", flagCode: "kn" },
  { name: "Sainte-Lucie", code: "LC", flagCode: "lc" },
  { name: "Saint-Marin", code: "SM", flagCode: "sm" },
  { name: "Saint-Vincent-et-les-Grenadines", code: "VC", flagCode: "vc" },
  { name: "Salomon", code: "SB", flagCode: "sb" },
  { name: "Salvador", code: "SV", flagCode: "sv" },
  { name: "Samoa", code: "WS", flagCode: "ws" },
  { name: "São Tomé-et-Príncipe", code: "ST", flagCode: "st" },
  { name: "Sénégal", code: "SN", flagCode: "sn" },
  { name: "Serbie", code: "RS", flagCode: "rs" },
  { name: "Seychelles", code: "SC", flagCode: "sc" },
  { name: "Sierra Leone", code: "SL", flagCode: "sl" },
  { name: "Singapour", code: "SG", flagCode: "sg" },
  { name: "Slovaquie", code: "SK", flagCode: "sk" },
  { name: "Slovénie", code: "SI", flagCode: "si" },
  { name: "Somalie", code: "SO", flagCode: "so" },
  { name: "Soudan", code: "SD", flagCode: "sd" },
  { name: "Soudan du Sud", code: "SS", flagCode: "ss" },
  { name: "Sri Lanka", code: "LK", flagCode: "lk" },
  { name: "Suède", code: "SE", flagCode: "se" },
  { name: "Suisse", code: "CH", flagCode: "ch" },
  { name: "Suriname", code: "SR", flagCode: "sr" },
  { name: "Syrie", code: "SY", flagCode: "sy" },
  { name: "Tadjikistan", code: "TJ", flagCode: "tj" },
  { name: "Tanzanie", code: "TZ", flagCode: "tz" },
  { name: "Tchad", code: "TD", flagCode: "td" },
  { name: "Tchéquie", code: "CZ", flagCode: "cz" },
  { name: "Thaïlande", code: "TH", flagCode: "th" },
  { name: "Timor oriental", code: "TL", flagCode: "tl" },
   { name: "Togo", code: "TG", flagCode: "tg" },
  { name: "Tonga", code: "TO", flagCode: "to" },
  { name: "Trinité-et-Tobago", code: "TT", flagCode: "tt" },
  { name: "Tunisie", code: "TN", flagCode: "tn" },
  { name: "Turkménistan", code: "TM", flagCode: "tm" },
  { name: "Turquie", code: "TR", flagCode: "tr" },
  { name: "Tuvalu", code: "TV", flagCode: "tv" },
  { name: "Ukraine", code: "UA", flagCode: "ua" },
  { name: "Uruguay", code: "UY", flagCode: "uy" },
  { name: "Vanuatu", code: "VU", flagCode: "vu" },
  { name: "Vatican", code: "VA", flagCode: "va" },
  { name: "Venezuela", code: "VE", flagCode: "ve" },
  { name: "Vietnam", code: "VN", flagCode: "vn" },
  { name: "Yémen", code: "YE", flagCode: "ye" },
  { name: "Zambie", code: "ZM", flagCode: "zm" },
  { name: "Zimbabwe", code: "ZW", flagCode: "zw" }
]

export default countries