import { PERMISSIONS } from "./permissions";

const FULL_ACCESS = Object.values(PERMISSIONS);

const READ_ONLY = [PERMISSIONS.USER_VIEW, PERMISSIONS.COURS_VIEW, PERMISSIONS.ACTUALITE_VIEW];

const TEACHER_ACCESS = [
  PERMISSIONS.ENSEIGNANT_CREATE,
  PERMISSIONS.ENSEIGNANT_UPDATE,
  PERMISSIONS.ENSEIGNANT_DELETE,
  PERMISSIONS.ENSEIGNANT_VIEW,
];

const ACADEMIC_FULL_ACCESS = [
  PERMISSIONS.FILIERE_CREATE, PERMISSIONS.FILIERE_UPDATE, PERMISSIONS.FILIERE_DELETE, PERMISSIONS.FILIERE_VIEW,
  PERMISSIONS.UE_CREATE, PERMISSIONS.UE_UPDATE, PERMISSIONS.UE_DELETE, PERMISSIONS.UE_VIEW,
  PERMISSIONS.UV_CREATE, PERMISSIONS.UV_UPDATE, PERMISSIONS.UV_DELETE, PERMISSIONS.UV_VIEW,
  PERMISSIONS.EVALUATION_CREATE, PERMISSIONS.EVALUATION_UPDATE, PERMISSIONS.EVALUATION_DELETE, PERMISSIONS.EVALUATION_VIEW,
  PERMISSIONS.SALLE_CREATE, PERMISSIONS.SALLE_UPDATE, PERMISSIONS.SALLE_DELETE, PERMISSIONS.SALLE_VIEW,
  PERMISSIONS.ETUDIANT_CREATE, PERMISSIONS.ETUDIANT_UPDATE, PERMISSIONS.ETUDIANT_DELETE, PERMISSIONS.ETUDIANT_VIEW,
  PERMISSIONS.GROUPE_CREATE, PERMISSIONS.GROUPE_UPDATE, PERMISSIONS.GROUPE_DELETE, PERMISSIONS.GROUPE_VIEW,
  PERMISSIONS.PERIODE_CREATE, PERMISSIONS.PERIODE_UPDATE, PERMISSIONS.PERIODE_DELETE, PERMISSIONS.PERIODE_VIEW,
  PERMISSIONS.RELEVE_CREATE, PERMISSIONS.RELEVE_VIEW,
  PERMISSIONS.ACTUALITE_CREATE, PERMISSIONS.ACTUALITE_UPDATE, PERMISSIONS.ACTUALITE_DELETE, PERMISSIONS.ACTUALITE_VIEW,
];

export const roleAccess = {
  informaticien: [...FULL_ACCESS],
  "directeur-general-adjoint": [...FULL_ACCESS],
  admin: [...FULL_ACCESS],
  "directeur-general": [...FULL_ACCESS],

  // Rôles à accès restreint RH (pas de suppression, pas de modification de rôle, pas d'ajout admin)

  "directeur-des-affaires-financieres": [...READ_ONLY],
  "responsable-administratif-et-financier": [...READ_ONLY],
  "directeur-des-etudes": [...READ_ONLY],

  // Rôles intermédiaires (pas d'accès admin)
  "logiticien-academique": [
    ...READ_ONLY,
    ...TEACHER_ACCESS,
    ...ACADEMIC_FULL_ACCESS,
    PERMISSIONS.COURS_CREATE,
    PERMISSIONS.COURS_UPDATE,
    PERMISSIONS.COURS_DELETE,
    PERMISSIONS.COURS_VIEW,
  ],
  "directeur-academique": [
    ...READ_ONLY,
    ...TEACHER_ACCESS,
    ...ACADEMIC_FULL_ACCESS,
    PERMISSIONS.COURS_CREATE,
    PERMISSIONS.COURS_UPDATE,
    PERMISSIONS.COURS_DELETE,
    PERMISSIONS.COURS_VIEW,
  ],

  // Marketing: Accès en lecture seule aux éléments académiques
  "responsable-marketing": [
    ...READ_ONLY,
    PERMISSIONS.FILIERE_VIEW,
    PERMISSIONS.UE_VIEW,
    PERMISSIONS.UV_VIEW,
    PERMISSIONS.EVALUATION_VIEW,
    PERMISSIONS.SALLE_VIEW,
    PERMISSIONS.ETUDIANT_VIEW,
    PERMISSIONS.GROUPE_VIEW,
    PERMISSIONS.PERIODE_VIEW,
    PERMISSIONS.RELEVE_VIEW,
  ],
};
